<?php
if( function_exists('acf_add_local_field_group') ):
    acf_add_local_field_group([
        'key' => 'group_post_accordion',
        'title' => 'Аккордеоны в записи',
        'fields' => [
            [
            'key' => 'field_post_accordion_blocks',
            'label' => 'Аккордеоны',
            'name' => 'accordion_blocks',
            'type' => 'flexible_content',
            'layouts' => [
                [
                'key' => 'layout_accordion_item',
                'name' => 'accordion_item',
                'label' => 'Блок аккордеона',
                'display' => 'block',
                'sub_fields' => [
                    [
                    'key' => 'field_accordion_title',
                    'label' => 'Заголовок',
                    'name' => 'title',
                    'type' => 'text',
                    ],
                    [
                    'key' => 'field_accordion_content',
                    'label' => 'Содержимое',
                    'name' => 'content',
                    'type' => 'wysiwyg',
                    ],
                ],
                ],
            ],
            'button_label' => 'Добавить аккордеон',
            ],
        ],
        'location' => [
            [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ],
            ],
        ],
    ]);
    acf_add_local_field_group([
        'key' => 'group_author_avatar',
        'title' => 'Фото автора',
        'fields' => [
            [
            'key' => 'field_author_avatar',
            'label' => 'Фото',
            'name' => 'profile_image',
            'type' => 'image',
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            ],
            [
            'key' => 'field_author_full_name',
            'label' => 'ФИО',
            'name' => 'full_name',
            'type' => 'text',
            ],
            [
            'key' => 'field_author_position',
            'label' => 'Должность',
            'name' => 'position',
            'type' => 'text',
            ],
        ],
        'location' => [
            [
            [
                'param' => 'user_role',
                'operator' => '==',
                'value' => 'author',
            ],
            ],
        ],
    ]);



    acf_add_local_field_group(array (
        'key' => 'group_55ebc364bb613',
        'title' => 'Конструктор страницы',
        'fields' => array (
            array (
                'key' => 'field_55ebc36f4be80',
                'label' => 'Добавьте необходимые блоки на страницу',
                'name' => 'ptg-builder',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'button_label' => 'Добавить',
                'min' => '',
                'max' => '',
                'layouts' => array (
                    array (
                        'key' => '55ebc3861f2ed',
                        'name' => 'ptg-spoiler',
                        'label' => 'Спойлер',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_55ebc3a64be81',
                                'label' => 'Заголовок',
                                'name' => 'spoiler-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_55ebc3b34be82',
                                'label' => 'Количество колонок',
                                'name' => 'spoiler-columns',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'one' => 'Одна',
                                    'two' => 'Две',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '',
                                'layout' => 'vertical',
                            ),
                            array (
                                'key' => 'field_55ebc3f44be83',
                                'label' => 'Контент',
                                'name' => 'spoiler-content',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_55ebc3b34be82',
                                            'operator' => '==',
                                            'value' => 'one',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array (
                                'key' => 'field_55ebc4074be84',
                                'label' => 'Левая колонка',
                                'name' => 'spoiler-content-left',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_55ebc3b34be82',
                                            'operator' => '==',
                                            'value' => 'two',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array (
                                'key' => 'field_55ebc41e4be85',
                                'label' => 'Правая колонка',
                                'name' => 'spoiler-content-right',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_55ebc3b34be82',
                                            'operator' => '==',
                                            'value' => 'two',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '55ebc6a29dc47',
                        'name' => 'ptg-text',
                        'label' => 'Текст',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_55ebc6b79dc48',
                                'label' => 'Показывать заголовок?',
                                'name' => 'text-title-boolean',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 1,
                            ),
                            array (
                                'key' => 'field_55ebc7909dc49',
                                'label' => 'Заголовок',
                                'name' => 'text-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_55ebc6b79dc48',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56d6c77fb7375',
                                'label' => 'Отображать рамку снизу?',
                                'name' => 'border-bottom-boolean',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                            ),
                            array (
                                'key' => 'field_55ebc7cc9dc4a',
                                'label' => 'Количество колонок',
                                'name' => 'text-columns',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'one' => 'Одна',
                                    'two' => 'Две',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '',
                                'layout' => 'vertical',
                            ),
                            array (
                                'key' => 'field_55ebc7ff9dc4b',
                                'label' => 'Контент',
                                'name' => 'text-content',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_55ebc7cc9dc4a',
                                            'operator' => '==',
                                            'value' => 'one',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array (
                                'key' => 'field_55ebc83a9dc4d',
                                'label' => 'Левая колонка',
                                'name' => 'text-content-left',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_55ebc7cc9dc4a',
                                            'operator' => '==',
                                            'value' => 'two',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array (
                                'key' => 'field_55ebc8559dc4e',
                                'label' => 'Правая колонка',
                                'name' => 'text-content-right',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_55ebc7cc9dc4a',
                                            'operator' => '==',
                                            'value' => 'two',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c307f205184',
                        'name' => 'ptg-contacts',
                        'label' => 'Контакты',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56c307f205186',
                                'label' => 'Заголовок',
                                'name' => 'contacts-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56c308320518b',
                                'label' => 'Карта',
                                'name' => 'contacts-map',
                                'type' => 'google_map',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'center_lat' => '',
                                'center_lng' => '',
                                'zoom' => '',
                                'height' => '',
                            ),
                            array (
                                'key' => 'field_56c308510518c',
                                'label' => 'Телефон',
                                'name' => 'contacts-phone',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56c308600518d',
                                'label' => 'E-mail',
                                'name' => 'contacts-email',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56c308850518e',
                                'label' => 'Адрес',
                                'name' => 'contacts-address',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c308e30518f',
                        'name' => 'ptg-jumbotron',
                        'label' => 'Банер',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56c308e305190',
                                'label' => 'Заголовок',
                                'name' => 'jumbotron-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56c308e305191',
                                'label' => 'Описание',
                                'name' => 'jumbotron-description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => 'wpautop',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56c308e305192',
                                'label' => 'Файл',
                                'name' => 'jumbotron-file',
                                'type' => 'file',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'library' => 'all',
                                'min_size' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c3095a05195',
                        'name' => 'ptg-incut',
                        'label' => 'Врезка',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56c3095a05196',
                                'label' => 'Контент',
                                'name' => 'incut-content',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c3099805199',
                        'name' => 'ptg-articles',
                        'label' => 'Статьи',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56c309980519a',
                                'label' => 'Заголовок',
                                'name' => 'articles-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c30ddf4da02',
                        'name' => 'ptg-partners',
                        'label' => 'Партнеры',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56c30ddf4da03',
                                'label' => 'Заголовок',
                                'name' => 'partners-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56c30dff4da04',
                                'label' => 'Изображения',
                                'name' => 'partners-images',
                                'type' => 'gallery',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => '',
                                'max' => '',
                                'preview_size' => 'full',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c30e5d4da05',
                        'name' => 'ptg-clients',
                        'label' => 'Клиенты',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56c30e5d4da06',
                                'label' => 'Заголовок',
                                'name' => 'clients-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56c30e5d4da07',
                                'label' => 'Изображения',
                                'name' => 'clients-images',
                                'type' => 'gallery',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => '',
                                'max' => '',
                                'preview_size' => 'full',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c30e9f4da08',
                        'name' => 'ptg-video',
                        'label' => 'Видео',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56c30e9f4da09',
                                'label' => 'Заголовок',
                                'name' => 'video-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c30ebf4da0b',
                        'name' => 'ptg-projects',
                        'label' => 'Проекты',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56c30ebf4da0c',
                                'label' => 'Заголовок',
                                'name' => 'projects-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c30edd4da0d',
                        'name' => 'ptg-gallery',
                        'label' => 'Фотогалерея',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56da8eafee787',
                                'label' => 'Показывать заголовок?',
                                'name' => 'gallery-title-boolean',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 1,
                            ),
                            array (
                                'key' => 'field_56c30edd4da0e',
                                'label' => 'Заголовок',
                                'name' => 'gallery-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_56da8eafee787',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56c30f074da0f',
                                'label' => 'Изображения',
                                'name' => 'gallery-images',
                                'type' => 'gallery',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => '',
                                'max' => '',
                                'preview_size' => 'full',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c30f414da10',
                        'name' => 'ptg-services',
                        'label' => 'Услуги',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56c30f414da11',
                                'label' => 'Заголовок',
                                'name' => 'services-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c30f784da13',
                        'name' => 'ptg-feedback',
                        'label' => 'Форма',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56d97e8e1d3a5',
                                'label' => 'Показывать заголовок?',
                                'name' => 'feedback-title-boolean',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 1,
                            ),
                            array (
                                'key' => 'field_56c30f784da14',
                                'label' => 'Заголовок',
                                'name' => 'feedback-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_56d97e8e1d3a5',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56d97edb1d3a6',
                                'label' => 'Показывать подзаголовок?',
                                'name' => 'feedback-subtitle-boolean',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                            ),
                            array (
                                'key' => 'field_56d97e301d3a4',
                                'label' => 'Подзаголовок',
                                'name' => 'feedback-subtitle',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_56d97edb1d3a6',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56c31edc956c4',
                                'label' => 'Выберите форму',
                                'name' => 'feedback-form',
                                'type' => 'post_object',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array (
                                    0 => 'wpcf7_contact_form',
                                ),
                                'taxonomy' => array (
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'return_format' => 'id',
                                'ui' => 1,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c31f9bb5d81',
                        'name' => 'ptg-section',
                        'label' => 'Секция',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56c31f9bb5d82',
                                'label' => 'Заголовок',
                                'name' => 'section-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56c323ce2db81',
                                'label' => 'Содержимое секции',
                                'name' => 'section-content',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'text' => 'Текст',
                                    'spoiler' => 'Спойлер',
                                    'carousel' => 'Карусель',
                                    'slider' => 'Слайдер',
                                    'form' => 'Форма',
                                ),
                                'default_value' => array (
                                    '' => '',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 1,
                                'ajax' => 0,
                                'placeholder' => '',
                                'disabled' => 0,
                                'readonly' => 0,
                            ),
                            array (
                                'key' => 'field_56c325022db82',
                                'label' => 'Карусель',
                                'name' => 'carousel',
                                'type' => 'gallery',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_56c323ce2db81',
                                            'operator' => '==',
                                            'value' => 'carousel',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => '',
                                'max' => '',
                                'preview_size' => 'full',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array (
                                'key' => 'field_56c325512db83',
                                'label' => 'Слайдер',
                                'name' => 'slider',
                                'type' => 'gallery',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_56c323ce2db81',
                                            'operator' => '==',
                                            'value' => 'slider',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => '',
                                'max' => '',
                                'preview_size' => 'full',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array (
                                'key' => 'field_56c325842db84',
                                'label' => 'Спойлер',
                                'name' => 'spoiler',
                                'type' => 'flexible_content',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_56c323ce2db81',
                                            'operator' => '==',
                                            'value' => 'spoiler',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'button_label' => 'Добавить',
                                'min' => '',
                                'max' => '',
                                'layouts' => array (
                                    array (
                                        'key' => '56c3260461596',
                                        'name' => 'spoiler-settings',
                                        'label' => 'Настройки спойлера',
                                        'display' => 'block',
                                        'sub_fields' => array (
                                            array (
                                                'key' => 'field_56c3264b2db85',
                                                'label' => 'Заголовок',
                                                'name' => 'spoiler-title',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array (
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                                'readonly' => 0,
                                                'disabled' => 0,
                                            ),
                                            array (
                                                'key' => 'field_56c326602db86',
                                                'label' => 'Количество колонок',
                                                'name' => 'spoiler-columns',
                                                'type' => 'radio',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array (
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'choices' => array (
                                                    'one' => 'Одна',
                                                    'two' => 'Две',
                                                ),
                                                'other_choice' => 0,
                                                'save_other_choice' => 0,
                                                'default_value' => '',
                                                'layout' => 'vertical',
                                            ),
                                            array (
                                                'key' => 'field_56c326b02db87',
                                                'label' => 'Контент',
                                                'name' => 'spoiler-content',
                                                'type' => 'wysiwyg',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array (
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'tabs' => 'all',
                                                'toolbar' => 'full',
                                                'media_upload' => 1,
                                            ),
                                            array (
                                                'key' => 'field_56c326d22db88',
                                                'label' => 'Левая колонка',
                                                'name' => 'spoiler-content-left',
                                                'type' => 'wysiwyg',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array (
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'tabs' => 'all',
                                                'toolbar' => 'full',
                                                'media_upload' => 1,
                                            ),
                                            array (
                                                'key' => 'field_56c326e52db89',
                                                'label' => 'Правая колонка',
                                                'name' => 'spoiler-content-right',
                                                'type' => 'wysiwyg',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array (
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'tabs' => 'all',
                                                'toolbar' => 'full',
                                                'media_upload' => 1,
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56c70c47c6927',
                        'name' => 'ptg-alert',
                        'label' => 'Рамка',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56c70c6ac6932',
                                'label' => 'Содержимое',
                                'name' => 'alert-content',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56da9db382bf3',
                        'name' => 'ptg-about',
                        'label' => 'О нас',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56da9dc882bf5',
                                'label' => 'Заголовок',
                                'name' => 'about-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56da9dd782bf6',
                                'label' => 'Контент',
                                'name' => 'about-content',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array (
                                'key' => 'field_56da9df382bf7',
                                'label' => 'Изображение',
                                'name' => 'about-img',
                          'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'full',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '56daba500668a',
                        'name' => 'ptg-discover',
                        'label' => 'Узнать',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_56daba500668b',
                                'label' => 'Заголовок',
                                'name' => 'discover-title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_56daba500668c',
                                'label' => 'Изображение',
                                'name' => 'discover-image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'project',
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'service',
                ),
            ),
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'potaga.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'the_content',
        ),
    ));

    acf_add_local_field_group(array (
        'key' => 'group_56beaf33310f3',
        'title' => 'Параметры видео',
        'fields' => array (
            array (
                'key' => 'field_56beaf3e69dc4',
                'label' => 'Ссылка на видео',
                'name' => 'ptg-video',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_56beaf8b21ba9',
                'label' => 'Миниатюра видео',
                'name' => 'ptg-video-thumbnail',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'video',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_55ddb13110a16',
        'title' => 'Параметры проекта',
        'fields' => array (
            array (
                'key' => 'field_55e1865b911df',
                'label' => 'Изображение шапки',
                'name' => 'potinni-project-header',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'full',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array (
                'key' => 'field_55f02b0ceca5d',
                'label' => 'Миниатюра проекта',
                'name' => 'potinni-project-thumbnail',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'project',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'the_content',
        ),
    ));

    acf_add_local_field_group(array (
        'key' => 'group_55e18ddc5231c',
        'title' => 'Параметры статьи',
        'fields' => array (
            array (
                'key' => 'field_55e18de436ddb',
                'label' => 'Изображение шапки',
                'name' => 'potinni-post-header',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'full',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_55dddb8568808',
        'title' => 'Параметры услуги',
        'fields' => array (
            array (
                'key' => 'field_55dddb980cd26',
                'label' => 'Описание',
                'name' => 'ptg-service-description',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_55e5abe19ebd6',
                'label' => 'Изображение шапки',
                'name' => 'ptg-service-header',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'full',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array (
                'key' => 'field_55ebee836dc4d',
                'label' => 'Изображение услуги',
                'name' => 'ptg-service-image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'service',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'the_content',
        ),
    ));

endif;